version: '3.1'

networks:
  hedera-app-network:

services:

  hedera-mysql-service:
    image: 'mysql:8.0.23'
    container_name: hedera-mysql-service
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      ./config/.env.mysql.dev
    volumes:
      - 'dbdata:/var/lib/mysql'
      - ./config:/docker-entrypoint-initdb.d
    ports:
      - 37117:3306
    networks:
      - hedera-app-network

  hedera-mongodb-service:
    image: 'mongo:latest'
    container_name: hedera-mongodb-service
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: pwc-bat-admin
      MONGO_INITDB_ROOT_PASSWORD: pwc-bat-admin-pass
    volumes:
      - 'mongodbdata:/data/db'
      - './config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
    networks:
      - hedera-app-network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_SERVER: hedera-mongodb-service
      ME_CONFIG_MONGODB_ADMINUSERNAME: pwc-bat-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwc-bat-admin-pass
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - hedera-app-network

  hedera-integration-node:
    container_name: hedera-integration-node
    build:
      dockerfile: dockerfile.dev
      context: ../HederaIntegrationNode
    restart: unless-stopped
    ports:
      - 8181:8181
    volumes:
      - ../HederaIntegrationNode:/usr/src/app
    depends_on:
      - hedera-mongodb-service
    networks:
      - hedera-app-network
  
  hedera-web-service-01:
    container_name: hedera-web-service-01
    build:
      dockerfile: dockerfile-01.dev
      context: ../HederaWebService
    restart: unless-stopped
    ports:
      - "8001:11136"
    volumes:
      - /usr/src/app/node_modules
      - ../HederaWebService:/usr/src/app
      - ../HederaWebServiceData01:/usr/src/data
    networks:
      - hedera-app-network
    depends_on:
      - hedera-mysql-service
      - hedera-integration-node

  hedera-web-service-02:
    container_name: hedera-web-service-02
    build:
      dockerfile: dockerfile-02.dev
      context: ../HederaWebService
    restart: unless-stopped
    ports:
      - "8002:11136"
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/builds
      - ../HederaWebService:/usr/src/app
      - ../HederaWebServiceData02:/usr/src/data
    networks:
      - hedera-app-network
    depends_on:
      - hedera-mysql-service
      - hedera-integration-node

  hedera-web-service-03:
    container_name: hedera-web-service-03
    build:
      dockerfile: dockerfile-03.dev
      context: ../HederaWebService
    restart: unless-stopped
    ports:
      - "8003:11136"
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/builds
      - ../HederaWebService:/usr/src/app
      - ../HederaWebServiceData03:/usr/src/data
    networks:
      - hedera-app-network
    depends_on:
      - hedera-mysql-service
      - hedera-integration-node

volumes:
  dbdata:
    driver: local
  mongodbdata:
    driver: local