version: '3.1'

networks:
  hedera-app-network:

services:

  hedera-mysql-service:
    image: 'mysql:8.0.23'
    container_name: hedera-mysql-service
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      ./config/.env.mysql.dev
    volumes:
      - 'dbdata:/var/lib/mysql'
    ports:
      - 37117:3306
    networks:
      - hedera-app-network
  
  hedera-web-service:
    container_name: hedera-web-service
    build:
      dockerfile: dockerfile.dev
      context: ../HederaWebService
    restart: unless-stopped
    ports:
      - "8001:11136"
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/build
      - ../HederaWebService:/usr/src/app
    networks:
      - hedera-app-network
    depends_on:
      - hedera-mysql-service

volumes:
  dbdata:
    driver: local