apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: hedera-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
  