apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
    - http:
        paths:
          - path: /web-01/*
            pathType: Prefix
            backend:
              service:
                name: hedera-web-service-01
                port: 
                  number: 8001
          - path: /web-02/*
            pathType: Prefix
            backend:
              service:
                name: hedera-web-service-02
                port: 
                  number: 8002
          - path: /web-03/*
            pathType: Prefix  
            backend:
              service:
                name: hedera-web-service-03
                port: 
                  number: 8003